// Shared Report Table Styles — inlined from jogi's lib/reports/styles.ts

export const T = {
    table: 'w-full text-xs',
    headerTitle: 'font-normal text-xs truncate',
    headerStat: 'font-normal text-xs',
    headerStatLabel: 'font-normal text-xs uppercase',
    headerCount: 'font-medium text-xs',
    th: 'text-gray-500 font-medium text-xs uppercase',
    cellLabel: 'overflow-hidden',
    input: 'bg-transparent border-none outline-none text-xs truncate',
    inputLabel: 'bg-transparent border-none outline-none text-xs font-medium truncate',
    inputPlaceholder: 'bg-transparent border-none outline-none text-xs text-gray-500 placeholder-gray-400 truncate',
    rowLabel: 'bg-transparent border-none outline-none text-xs font-medium text-gray-600 truncate',
    sectionTitle: 'font-normal text-xs',
    totalLabel: 'font-medium text-xs',
    totalValue: 'font-medium text-xs',
    footerLabel: 'font-bold',
    footerValue: 'font-bold',
    muted: 'text-xs text-gray-600',
    empty: 'text-xs text-gray-400 italic',
    cardLabel: 'text-xs font-medium',
    cardValue: 'text-xs font-semibold',
    // Summary table rows
    sumSubheaderRow: 'border-b-2 border-gray-300',
    sumSubheaderLabel: 'py-2 px-3 text-xs font-bold text-gray-800 uppercase tracking-wider',
    sumSubheaderCol: 'py-2 px-3 text-right text-xs font-bold text-gray-600',
    sumDataRow: 'border-b border-gray-100',
    sumDataLabel: 'py-1.5 px-3 text-gray-600 pl-5',
    sumDataValue: 'py-1.5 px-3 text-right tabular-nums text-gray-700',
    sumTotalRow: 'border-b bg-gray-50/80 border-gray-200',
    sumTotalLabel: 'py-1.5 px-3 font-bold text-gray-800',
    sumTotalValue: 'py-1.5 px-3 text-right tabular-nums font-bold text-gray-800',
    sumGrandtotalRow: 'border-b-2 bg-gray-100 border-gray-300',
} as const
